# Generated by Django 3.2.9 on 2022-01-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('1', 'LCD TV'), ('2', 'Computer'), ('3', 'Laptop'), ('4', 'Lamp'), ('5', 'Electric heater'), ('6', 'Air conditioner'), ('7', 'Mini-fridge'), ('8', 'Fan'), ('9', 'Extension cord'), ('10', 'Smartphone charger')], max_length=20),
        ),
    ]
