# Generated by Django 3.2.9 on 2022-01-04 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0002_alter_type_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliances',
            old_name='room_number',
            new_name='room',
        ),
    ]
