# Generated by Django 3.2.9 on 2022-01-04 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0003_rename_room_number_appliances_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliances',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.type'),
        ),
    ]
