# Generated by Django 3.2.9 on 2022-01-04 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0005_alter_type_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='type',
        ),
        migrations.AddField(
            model_name='actions',
            name='action',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actions',
            name='appliance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appliances.type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actions',
            name='summary',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Action_Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('appliance', models.ManyToManyField(to='appliances.Appliances')),
            ],
        ),
    ]
