# Generated by Django 3.2.9 on 2022-01-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0006_auto_20220104_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action_appliance',
            name='appliance',
        ),
        migrations.AddField(
            model_name='action_appliance',
            name='type',
            field=models.ManyToManyField(to='appliances.Type'),
        ),
    ]
