# Generated by Django 3.2.9 on 2022-01-04 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0007_auto_20220104_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='action_appliance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appliances.action_appliance'),
            preserve_default=False,
        ),
    ]
