# Generated by Django 3.2.9 on 2022-01-04 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0008_actions_action_appliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='actions',
            name='action',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='actions',
            name='appliance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appliances.appliances'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='summary',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
