# Generated by Django 3.2.9 on 2022-01-04 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0009_auto_20220104_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='action',
        ),
        migrations.RemoveField(
            model_name='actions',
            name='summary',
        ),
    ]
