# Generated by Django 3.2.9 on 2022-01-05 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0011_appliances_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliances',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 5, 13, 21, 0, 175373, tzinfo=utc)),
        ),
    ]
