# Generated by Django 3.2.9 on 2022-01-05 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0012_alter_appliances_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliances',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 5, 14, 26, 44, 730765, tzinfo=utc)),
        ),
    ]
