# Generated by Django 3.2.9 on 2022-01-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='12345678', max_length=30)),
                ('room_number', models.IntegerField()),
                ('square_meters', models.IntegerField()),
                ('windows', models.IntegerField()),
                ('is_insulated', models.BooleanField(default=False)),
                ('is_normal', models.BooleanField(default=False)),
                ('has_bathroom', models.BooleanField(default=False)),
            ],
        ),
    ]
