# Generated by Django 3.2.9 on 2022-01-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20220103_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='windows',
            field=models.IntegerField(null=True),
        ),
    ]
