# Generated by Django 3.2.9 on 2022-01-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20220103_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
