# Generated by Django 3.2.9 on 2022-01-05 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_room_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 5, 13, 21, 0, 173197, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 5, 13, 21, 0, 172073, tzinfo=utc)),
        ),
    ]
