# Generated by Django 3.2.9 on 2022-01-05 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_auto_20220105_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 5, 14, 26, 44, 725375, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='room',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 5, 14, 26, 44, 720978, tzinfo=utc)),
        ),
    ]
